### ISSUE TITLE
How can I custom keys in validation?

### ISSUE THREAD

**Issue by projecthl2** [hanami/validations#132]
Hi, I read [README](https://github.com/hanami/validations#custom-error-messages) and understood to custom my error messages.

But I have a question... how to custom keys (in this case, like "age".) in validation?

```yaml
en:
  errors:
    email?: "must be an email"

    rules:
      signup:
        age: # want to set custom value here.
          gt?: "must be an adult"
```

It is serious problem for me, because I'm Japanese and I work in Japan. I have to use Japanese error messages at all to use `Hanami` in our products.

I checked issues, but I am sorry if I duplicated.

Thanks.

**Comment by cllns** [comment]
Sorry you're having trouble!

I don't think we expect the keys to be displayed to the user. Notice the message is just "must be an adult", which is a message about the person, not the age specifically. "must be 18 or older" would be the message for the age. Does that make sense? 

You could work around this by *not* showing they key, and putting that translation into the value.

```
en:
  errors:
    email?: "must be an email"

    rules:
      signup:
        age: 
          gt?: # japanese for "age must be 18 or older"
```

If you do want to show the key, I think you can look at leveraging the `i18n` gem for translating that.

```
jp:
  age: 年齢
```
(I don't know if this translation is correct, it was Google Translate's first result :) )
